version: "3"

services:
  server:
    build: ./server/
    image: reversi_server
    container_name: reversi_server
    tty: true
    ports:
      - 8888:8888
    environment:
      - GOPATH=/server

  app:
    build: ./app/
    image: reversi_app
    container_name: reversi_app
    tty: true
    working_dir: /app
    ports:
      - 80:8080
