version: "3"

services:
  server:
    image: golang:latest
    container_name: server
    tty: true
    volumes:
      - ./server:/server
    working_dir: /server
    ports:
      - 8888:8888
    environment:
      - GOPATH=/server
    command: [/bin/bash] # TODO
  app:
    image: vue
    container_name: app
    tty: true
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - 80:8080
    # command: [/bin/bash] # TODO
